### ISSUE TITLE
SendKeys : System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/PointCloudConverter#36]
> child stdout:
> Unhandled exception.
> child stdout:
> System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully.
>    at System.Windows.Forms.SendKeys.SendInput(ReadOnlySpan`1 oldKeyboardState, SKEvent[] previousEvents)
>    at System.Windows.Forms.SendKeys.Send(String keys, Control control, Boolean wait)

one other issue with sendkeys is that, if the console itself is not active/focused, it sends Sendkey into current active window!

**Comment by unitycoder** [comment]
probably fixed in https://github.com/unitycoder/PointCloudConverter/commit/178550938dea45a40d08ebd04f30d89c9d866f06
(removed sendkey usage)
